README.md
This demo fixes the README file.
=> This is a demonstration.

py/legacypipe/brick-to-ccds.py, py/legacypipe/forced-photom-decam.py, py/legacypipe/queue-calibs.py, py/legacypipe/run-calib.py, py/legacypipe/runbrick.py, py/legacypipe/write_initial_catalog.py
=> replace optparse with argparse (Fixes #45).

py/legacypipe/bok.py, py/legacypipe/image.py
I pulled master into this version, fixed conflicts in bok.py, and pushed to remote. Tested and seems good.
=> 90prime.* config files now used to create SExtractor and PSFex files for Bok images. 

bin/generate-sweep-files.py, bin/generate-sweep-files.slurm.cori, bin/match-boss-catalogue-dr12q.slurm.cori, bin/match-boss-catalogue-specObj-dr12.slurm.cori, bin/match-boss-catalogue-superset-dr12q.slurm.cori, bin/match-boss-catalogue.py
Update the example nersc scripts and scripts for sweep files and matched catalogues. 
They all run on NERSC on the current DR3 data files (files that are being processed will be ignored)
#98
=> DR3 sweep match

py/legacyanalysis/decals_sim.py, py/legacyanalysis/decals_sim_plots.py, py/legacyanalysis/decals_sim_unit_test.py, py/legacyanalysis/fdr-figures.py, py/submit_elg.sh, py/test/runbrick_test.py
1) Now make the input flux the flux contained in 7''/0.262 pixel aperture on pixelized PSFs. This reduces the 2-3% mag difference from Durham to 0.3-0.6%. The remaining error is due to image invvar, imperfect sky subtraction, and/or tractor.
2) decals_sim.py is now MUCH more modular
3) test/runbrick_test.py has the code to run our "run to completion test" but it is commented out until we can build Galsim within Travis.
=> Fix flux normalization to 7'' aperture

py/legacypipe/format_catalog.py, py/legacypipe/runbrick.py, py/legacypipe/runs.py, py/legacypipe/survey.py
Oops, looks like I have a couple of unrelated commits in here too!
=> Experiment with adding a "--run" option to runbrick.py

py/legacypipe/catalog.py, py/legacypipe/oneblob.py, py/legacypipe/runbrick.py, py/legacypipe/survey.py, py/test/runbrick_test.py
This also fixes #128 (accidentally made the fix in this branch rather than master)
=> Add --rex option to runbrick.py

py/legacypipe/runbrick.py
This requires new feature in the "master" version of the tractor code, so I didn't push this feature to legacypipe master yet.
=> implement PSF broadening for WISE forced photometry.

py/legacypipe/runbrick.py, py/obiwan/decals_sim.py
just call decals_sim.py with --early_coadds --stage image_coadds
=> obiwan can now make cutouts at exposure level if desired

bin/pipebrick.sh, py/legacyanalysis/create_testcase.py, py/legacypipe/annotate-ccds.py, py/legacypipe/image.py, py/legacypipe/oneblob.py, py/legacypipe/runbrick.py
Adds command-line options in runbrick.py and annotate-ccds.py to --normalize-psf.
=> Normalize psf merge

doc/conf.py, py/legacypipe/detection.py, py/legacypipe/runbrick.py, py/legacypipe/survey.py, py/test/runbrick_test.py
--gaia is default
--normalize-psf is default
=> Change runbrick.py defaults to match what we want to do for DR7

py/legacypipe/detection.py, py/legacypipe/image.py, py/legacypipe/runbrick.py
=> make saturated-pixel masks per-band, not overall

py/legacypipe/format_catalog.py, py/legacypipe/runbrick.py
1" Gaussian seeing, 1.5" diameter fibers
=> Compute FIBERFLUX and FIBERTOTFLUX

py/legacypipe/runbrick.py, py/legacypipe/survey.py
=> add --unwise-coadds flag to write out FITS and JPEGs of WISE tiles overlapping

py/legacypipe/runbrick.py, py/legacypipe/survey.py
... from the checkpoints and mark unfinished ones with a maskbits flag
=> add --bail-out option to write out all finished blobs

py/legacypipe/format_catalog.py, py/legacypipe/oneblob.py, py/legacypipe/runbrick.py, py/legacypipe/survey.py
- convert "brightstarinblob" flag into "brightblob" bitmask
- add medium-bright stars to maskbits product
=> Brightblob -- handle bright stars outside brick

bin/legacypipe-env
Add an environment variable to the new large galaxies catalog.
=> add LARGEGALAXIES_DIR env

py/legacypipe/runbrick.py
Four-line fix to a bug introduced in #239.  Not ready to merge yet -- still testing.
=> fix numpy.extend() bug introduced in #239

docker-intel/Dockerfile, py/legacypipe/runbrick.py
Among other things, this allows "None" results to be recorded, so that they don't have to be recomputed.
=> In checkpoint files, record brick name and blob number

py/legacypipe/unwise.py
=> make WISE flux ivars float32

bin/legacypipe-env, py/legacypipe/format_catalog.py, py/legacypipe/reference.py
Points to new Gaia chunks files, and reads and propagates extra columns from them.
=> New Gaia columns

bin/match-external-catalog.py
Fixes #213.
May need recent versions of numpy (1.14 etc). Not so sure.
=> Assign structured arrays by field names.

bin/generate-sweep-files.py
Add the `REF_CAT` column to the sweeps files.
=> Add REF_CAT to the sweeps

bin/runcalibs-shifter.sh, py/legacypipe/image.py, py/legacypipe/reference.py, py/legacyzpts/legacy_zeropoints.py, py/legacyzpts/merge_calibs.py
Not so much logging, from source extractor, psfex, and our code.
=> Make calibs much quieter

py/legacypipe/detection.py, py/legacypipe/image.py, py/legacypipe/oneblob.py, py/legacypipe/reference.py, py/legacypipe/runbrick.py, py/legacypipe/runbrick_plots.py, py/legacypipe/survey.py, py/legacypipe/utils.py, py/legacyzpts/legacy_zeropoints.py
This also makes significant changes to the way to set maximum galaxy radii!
=> Resolve sources that are in the LSLGA *and* Gaia

py/legacypipe/detection.py, py/legacypipe/halos.py, py/legacypipe/oneblob.py, py/legacypipe/reference.py, py/legacypipe/runbrick.py, py/legacypipe/survey.py
=> Adjust masking logic

py/legacypipe/ps1cat.py, py/legacyzpts/annotate_ccds.py, py/legacyzpts/legacy_zeropoints.py
Addresses #348; still testing.
=> use ps1cat_dir environment variable in legacy_zeropoints

py/legacyzpts/legacy_zeropoints.py
We were accidentally moving the Gaia stars to the epoch of observation TWICE.
=> Clean up zeropoints code, eliminate double-moving Gaia stars

py/legacypipe/image.py, py/legacypipe/runbrick.py
So far:
* Various fixes needed to work with old calibration files (here, tested with DR7 calibs).
* One bug prompted by #323 (@dstndstn please check the hack to `stage_srcs`).
=> various fixes prompted by recent activity but focused on #344

py/legacypipe/halos.py, py/legacypipe/runbrick.py
=> fix some errors when Gaia medium star exists

py/legacypipe/runbrick.py, py/legacypipe/survey.py
=> grz bands only

py/legacypipe/image.py, py/legacypipe/outliers.py, py/legacypipe/runbrick.py
Avoid masking the cores of Gaia stars in our outlier masking.
=> Don't mask reference stars

docker-nersc/Dockerfile, py/legacypipe/halos.py, py/legacypipe/runbrick.py
Doesn't work well enough for prime time!
=> Star halos -- implement subtraction, but turn it off

docker-nersc/Dockerfile, py/legacypipe/bok.py, py/legacypipe/coadds.py, py/legacypipe/detection.py, py/legacypipe/halos.py, py/legacypipe/image.py, py/legacypipe/oneblob.py, py/legacypipe/outliers.py, py/legacypipe/runbrick.py, py/legacypipe/runbrick_plots.py, py/legacypipe/survey.py, py/legacypipe/unwise.py
- Use new astrometry resample_with_wcs API for pixel int sizes
- For HybridPSF, use single-component Gaussian with CCD-table fwhm value
- avoid np.round
=> Some speedups

py/legacypipe/bits.py, py/legacypipe/bright-neighbors.py, py/legacypipe/cfht.py, py/legacypipe/coadds.py, py/legacypipe/decam.py, py/legacypipe/image.py, py/legacypipe/oneblob.py, py/legacypipe/outliers.py, py/legacypipe/runbrick.py, py/legacypipe/runbrick_plots.py, py/legacypipe/survey.py
=> Move bit-field definitions to legacypipe/bits.py

bin/generate-sweep-files.py
This PR adds `PSFDEPTH_W1` and `PSFDEPTH_W2` to the sweeps files.
=> Add WISE depths to sweep files

py/legacypipe/detection.py, py/legacypipe/runbrick.py
To not try to do source detection within large Galaxy and Globular Cluster regions
=> Add --bail-out-sources option

.circleci/config.yml, .travis.yml, bin/legacypipe-env, docker-nersc/Dockerfile, py/legacypipe/survey.py, py/legacypipe/unwise.py
WIP -- not ready to merge.
* Use the full filename to the large-galaxies catalog.
* Use the new `unwise_psf` repo.
Still need to test the code changes with (and without) the Docker container.
=> use new LARGEGALAXIES_CAT env and new unwise_psf

py/legacyzpts/legacy_zeropoints.py
=> recompute airmass for every MzLS exposure

docker-nersc/Dockerfile
Instead of python3.5 from old Debian (base image for NERSC's intel compiler containers)
=> build python3.7 from conda

py/legacypipe/reference.py
See [decam-data 2770], [desi-milkyway 639], and the email by Moustakas to chatter, desi-targets, and desi-bgs with the subject "selection of Gaia point sources in DR9".
We should wait for feedback from the relevant WGs before merging this.
=> be more conservative selecting Gaia stars

docker-nersc/Dockerfile, py/legacyzpts/annotate_ccds.py, py/legacyzpts/legacy_zeropoints.py
- fitsio 1.0.6
- fix weird issue writing expnum field
- fix annotated-ccds call of get_tractor_image
=> Calib fixes

bin/build-cluster-catalog.py
See thread in #491.  Note that I've branched from the `preburn-lslga` branch.  
@dstndstn if this looks OK can you please merge and then update the GC+PN layer in the viewer?
=> cluster updates

py/legacypipe/runbrick.py
Do not store NaN fiberfluxes.
Addresses #508
=> Nan fiberflux

py/legacypipe/unwise.py
Aaron & Eddie's suggested changes to unWISE pixel weighting
=> Wise weights

py/legacypipe/oneblob.py, py/legacypipe/runbrick.py
@dstndstn please take a quick look.
=> quick bug fixes

py/legacypipe/reference.py
This halves the radius of the BRIGHT mask.
=> Bright radius

py/legacypipe/decam.py, py/legacypipe/image.py, py/legacypipe/survey.py
=> initial implementation of sky template subtraction for DECam

py/legacypipe/runs.py
@dstndstn I know this isn't quite how you suggested I handle M33, but it works. In detail, I didn't want the `M33SurveyData` class to have to do the selection of the CCDs and instead went with the static files that @djschlegel made (although that's probably fragile so we should probably fix this).
=> add an M33 special run

py/legacypipe/fit_on_coadds.py
This only impacts me, so I plan to self-merge once tests pass.
=> updates to handle custom sky-subtraction

py/legacypipe/image.py, py/legacyzpts/legacy_zeropoints.py
=> Prelim sky

bin/filelist_maker.py, py/legacyzpts/legacy_zeropoints.py
The most important change here is making sure to only try to compute zero points for HDUs that exist in Mosaic in 90prime files.
This also adds some warning messages to legacy_zeropoints, changes the "failure" zero point to zero from np.nan, cleans up some stylistic issues in filelist_maker, and does a better job of finding raw file names and trimming file names down to the relevant parts for comparison with image_filename in survey-ccds files.
=> Use only existing HDUs in legacy_zeropoints and some miscellaneous tweaks

py/legacypipe/runbrick.py
Expand the exclusion zone around SGA large galaxies
=> Grow exclusion zone

py/legacypipe/decam.py, py/legacypipe/image.py
add a fix_saturation() call; apply it for DECam S19 for PLVER <= 4.9.0
=> Handle DECam S19 unmasked saturation

py/legacypipe/oneblob.py
not the DenseConstrainedOptimizer we use elsewhere.
=> During initial flux-only fitting (forced phot), use Ceres optimizer,

bin/forced-south.sh, py/legacypipe/forced_photom.py, py/legacypipe/halos.py, py/legacypipe/image.py, py/legacypipe/reference.py, py/legacypipe/survey.py
- find Gaia stars and subtract halos for DECam
- find SGA galaxies outside but still touching the chip and subtract them before forced-photometry
- read the full image area (don't trim all-masked edge pixels), so edge behavior better-defined
- set sky template and SGA and Gaia env. vars in script
=> Forced-phot: halo subtraction and SGA-outside-the-chip

py/legacyanalysis/coverage.ipynb, py/legacypipe/coadds.py, py/legacypipe/detection.py, py/legacypipe/fit_on_coadds.py, py/legacypipe/runbrick.py, py/legacypipe/survey.py
This also adds the --blob-dilate command-line arg.
=> Coadd tiers

py/legacypipe/decam.py, py/legacyzpts/legacy_zeropoints.py
=> Nominal zpts

py/legacypipe/format_catalog.py, py/legacypipe/runbrick.py
@dstndstn I believe that this addresses issue #693. Let me know what you think...
=> update typical number of WISE light curve epochs to 17

py/legacypipe/detection.py, py/legacypipe/farm.py, py/legacypipe/oneblob.py, py/legacypipe/runbrick.py, py/legacypipe/survey.py, py/legacypipe/utils.py, py/test/unit_tests.py
Also included: speed up deblending by only searching for a brighter blended source within 50 pixels.
=> Within CLUSTER mask, break large blobs into sub-blobs and process them in parallel

py/legacypipe/bits.py, py/legacypipe/oneblob.py, py/legacypipe/runbrick.py
Also add a MASKBITS bit to mark these blobs.
=> Add --sub-blob flag to enable sub-blob processing on any large blobs (not just CLUSTER mask)

py/legacypipe/units.py
For DR11.
- change 1/U^2 to U^(-2)
- change "nanomaggy" to "nanomaggies"
Per discussion in https://github.com/legacysurvey/legacysurvey/issues/158
=> Fix units header cards

py/legacypipe/galex.py
=> GALEX adaptive psf size
