py/legacyanalysis/get-brick-files.py
Adds a convenience function to just write out the set of images and calibration files one needs to run Tractor on a single brick.  Useful for transferring data to a laptop or non-NERSC server.
=> script to identify images and calibration files needed to process a brick

py/legacyanalysis/euclid.py, py/legacyanalysis/lsb.py, py/legacyanalysis/wise-cutouts.py, py/legacypipe/catalog.py, py/legacypipe/detection.py, py/legacypipe/forced_photom_decam.py, py/legacypipe/format_catalog.py, py/legacypipe/runbrick.py, py/legacypipe/survey.py, py/test/runbrick_test.py
- write intermediate tractor catalogs whose flux columns are just called "flux", not "decam_flux"
- add format_catalog.py module to convert intermediate catalogs into final catalogs
- call format_catalog from runbrick.py to produce catalogs consistent with DR3, for the moment
- various tidy-ups
=> Write intermediate tractor catalogs

py/legacypipe/survey.py
* if survey-ccds-*.kd.fits exist, read those file(s) as Astrometry.net/libkd KD-tree structures, and search for and read only nearby CCDs in survey.ccds_touching_wcs().
=> Add a KD-tree structure to the survey-CCDs table, to make ccds_touching_wcs way faster

bin/modulefiles/cori/legacysurvey, bin/modulefiles/cori/unwise_coadds, bin/modulefiles/cori/unwise_coadds_timeresolved
This updates the `LEGACY_SURVEY_DIR` for DR5 production and also updates the default location of the unwise module files in the desiproc scratch space.
=> update modules files for DR5 production

py/legacypipe/image.py
@dstndstn, what do you think?
I deleted a single line.
The bug is in the get_image_extent() function, which get_tractor_image relies on. Because the top of the func hardcoded "slc=None", the FULL ccd image is returned no matter what "slc" is asked for.
I found it when using your **amazing** create_testcase.py module. The image cutouts for full size CCDs not the 200x200 pixel region I was requesting. Eventually traced it to the above issue. I got the expected create_testcase results after deleting the above line...
=> bug in get_tractor_image()

py/legacyanalysis/ps1cat.py
Option to read either PS1 sources or matched PS1-Gaia sources
* the default is PS1, so any code that called ps1cat().get_stars() should still work as before
* do get PS1-Gaia matched-only sources set the kwarg "ps1_or_gaia= ps1_gaia" and "prefix = chunk"
Tested with Legacyzpts and works fine
=> added PS1/Gaia option to ps1cat

bin/dr6-envs.sh, bin/generate-sweep-files.slurm, bin/match-external-catalog.slurm
The Python from desiconda is sufficiently good for these applications. Switching to desiconda offloads the toolchain maintenance to desi collaboration.
This PR also adds the environment template (dr6-envs.sh) to the scripts, following the documentation in docs/ directory.
The next DR could simply make a fork of the file, change the paths in the envs, and update the jobs scripts to use the new one.
=> Update data scripts to use desiconda

py/legacypipe/format_catalog.py, py/legacypipe/image.py, py/legacypipe/oneblob.py, py/legacypipe/runbrick.py, py/test/runbrick_test.py
- unify Tycho-2 and Gaia reference star handling -- Tycho-2 stars now have their positions nailed down, same as Gaia stars.
- move Gaia stars to the epoch of Tycho-2 before matching
- force all sources within the same blob as a "bright" reference star to be PSF only
- "bright" defined, for now, as Tycho-2
- add "brightstarinblob" to output catalogs
- add reddening columns to output catalogs
- fix units of Tycho-2 RA,Dec uncertainties
=> Improved handling of Tycho-2 and Gaia DR2 reference stars

py/legacypipe/oneblob.py, py/legacypipe/runbrick.py
We found that if source detection changes, then checkpoint files can result in inconsistencies in the resulting catalogs (repeated sources, etc).
This adds checks for results read from the checkpoint files.
=> Check checkpoint files when reading

py/legacypipe/detection.py, py/legacypipe/image.py, py/legacypipe/runbrick.py
This PR includes a very minor change to `image` to return the (spline) sky model read from disk even if `subsky=False`.  This should have no impact on the pipeline because we *always* use `subsky=True`, but it's helpful for the testing I've been doing.
Second, in `detection.detection_maps` I found that some `wcs` objects returned height and width attributes that were float rather than integer, which causes issues with the subsequent bit of code, so they're explicitly cast as `int` here.
@dstndstn please feel free to reject or alter these changes but it would be good to resolve this PR while it's still fresh in my mind at least!
=> return sky model even if subsky=False

py/legacypipe/queue-calibs.py
Adds all of the test regions for DR8 to `queue-calibs.py` as `--region` options. Includes everything [on the wiki](https://desi.lbl.gov/trac/wiki/DecamLegacy/DR8testregions) and the new BASS/MzLS test regions.
=> add DR8 test regions to queue-calibs

py/legacypipe/queue-calibs.py
Add a new area to the DR8 test regions that includes overlap between DECaLS, MzLS and BASS.
=> Add new DR8 "overlap" test region

bin/match-external-catalog.py
On last Wednesday's telecon it was decided to increase the matching radius for external catalogs to 1.5". This PR does that.
Should address https://github.com/legacysurvey/legacypipe/issues/117.
=> increase matching radius for external catalogs to 1.5

bin/legacypipe-env, py/legacypipe/unwise.py
This brings the unWISE Catalog NEO4 PSF into legacypipe.  It also adds a modest arbitrary adjustment to the PSF normalization to bring the catalog's overall flux scale into agreement with unWISE.  Note that there is a small non-linearity so it's impossible to do this perfectly at all magnitudes.
This PR requires that unwise_psf also be updated to a recent version (i.e., since ~yesterday).  Otherwise unwise_psf.get_unwise_psf will not support the 'modelname' argument.
=> Bring unWISE Catalog PSF into legacypipe

py/legacypipe/reference.py
* Do not embiggen the initial large-galaxy radius by the 20% fudge factor.
* Account for the rough factor of two difference between the R(25) isophotal radius and the half-light radius.
* Rotate the initial position angle from LSLGA by 180 degrees to bring it into the `e1`, `e2` system.
Results compared to dr8b look better!
http://legacysurvey.org/viewer-dev?ra=20.5991&dec=-0.8754&zoom=14&layer=dr8b-decam
=> minor updates (improvements!) to how we seed LSLGA sources

.circleci/config.yml, py/legacypipe/image.py, py/legacypipe/runbrick.py, py/legacypipe/survey.py, py/legacypipe/unwise.py
Addresses #320.  Still testing; not quite ready to merge.
Note that previously this directory variable was called `background_dir`, which I changed to `unwise_modelsky_dir` to match the other unWISE directories (static + time-resolved stacks).
=> add unwise_modelsky_dir to output header(s) and as optional input to run_brick

py/legacyzpts/merge_calibs.py
Some of our DECam calibration failures are due to this bug in `fitsio.read_header`:
```
import fitsio
hdr = fitsio.FITSHDR()
hdr['PLPROCID'] = '89113e6'
fitsio.write('/tmp/1.fits', None, header=hdr)
hdr2 = fitsio.read_header('/tmp/1.fits')
print(hdr2['PLPROCID'])
-> 89113000000.0
```
We filed a ticket (https://github.com/esheldon/fitsio/issues/207) but in the meantime we're bypassing this problem by using `astropy.io.fits.getheader`.
=> use astropy.io.fits.getheader to bypass fitsio.read_header bug

py/legacypipe/decam.py
Per Frank, in various CP pipeline versions the CR and Streak DQ labels get mixed up.  Since our outlier masking seems to be working well, perhaps we should ignore both these masks.
See the final images in #323
=> Ignore both CR and Streak masks

py/legacypipe/runbrick.py
This simple PR allows the `LegacySurveyData().ccds` attribute to be populated when calling `stage_tims` directly.
Should be a non-controversial merge.
=> allow survey.ccds to be pre-populated

bin/update_ccd_cuts.py, py/legacyzpts/legacy_zeropoints.py, py/legacyzpts/psfzpt_cuts.py
This PR updates update_ccd_cuts.py to optionally patch in ubercal zero points, if a new --zeropoints argument is given.  Then the CCD_CUTS are updated given those new zero points.  Additionally, sig1 and the various depth fields are updated accordingly in the survey & annotated CCDs files.  
This PR also updates the handling of izY CCD_CUTS.  Previously these filters were given dummy nominal zero points of 0 in psfzpt_cuts.py, leading all good exposures to have CCD_CUTS of at least zpt_large.  Since the depth cut bit & too many bad CCDs bits have the annoying property of excluding everything that has been excluded for any other reason, these bits are also set.  This PR fixes at least the zero point issue by updating psfzpt_cuts.py to have more realistic values for nominal i and Y zero …
=> Add patching in of ucal zero points to update_ccd_cuts.py, and better handle izY ccd_cuts

py/legacyzpts/data/90prime-bad_expid.txt
I ran through the -photom files looking for images with a lot of stars marked as cosmic rays.  The above images are the worst cases, with more than 10% of stars marked as CRs and more than 5000 stars total.  Running through these, most are triggered by blobby/donut-like PSFs.  This PR adds those to the badexp list.  It looks like one could find ~10x more such images if one did CR-frac > 0.01 and nstar > 100,
=> Add images that trigger the CR flag to badexp file

validationtests/desi_image_validation4.py
I noticed that the extinction coefficients do not match with the description on the DR8 [website](http://legacysurvey.org/dr8/catalogs/#galactic-extinction-coefficients);
"_Eddie Schlafly has computed the extinction coefficients for the DECam filters through airmass=1.3, computed for a 7000K source spectrum as was done in the Appendix of Schlafly & Finkbeiner (2011). These coefficients are A / E(B-V) = 3.995, 3.214, 2.165, 1.592, 1.211, 1.064 (note that these are slightly different from the coefficients in Schlafly & Finkbeiner 2011)._"
=> Extinction coefficients fix

py/legacyzpts/data/90prime-bad_expid.txt
This commit marks the single duplicate raw exposure as bad.  See
https://github.com/legacysurvey/legacypipe/issues/398
for details.  On disk file name is
CP20160505/ksb_160506_123748_ooi_g_ls9.fits.fz
=> Mark duplicate raw exposure as bad

py/legacyzpts/data/decam-bad_expid.txt
Frank's reprocessing of DECam fixed a number of images with bugs in their processing.  These may now be removed from DR9.
I left 368186 in the bad_expid list because it is clear that there are significant scattering halos around the bright stars, so there are probably clouds.  721209, 736317, 780010, and 420479 also remain in the list, because we either didn't reprocess them, they had weird propid's that we wouldn't include anyway, or in the case of 420479, it looks like I accidentally transcribed that from the 'correct' 420749.   That's from a propid we no longer include.
=> Remove reprocessed, fixed exposures from bad_expid

py/legacypipe/image.py
In the reprocessed `mosaic` imaging, the early survey data used to be missing the `EXPNUM` header card, but now it's there and blank.  Capture this corner case.
=> corner case when EXPNUM is None

py/legacypipe/coadds.py, py/legacypipe/format_catalog.py, py/legacypipe/oneblob.py, py/legacypipe/outliers.py, py/legacypipe/runbrick.py, py/legacypipe/utils.py
- dropped "brightblob" column
Tractor catalog header currently has:
```
MB_NPRIM=                    1 / Maskbit: non-primary brick area
MB_BRIGH=                    2 / Maskbit: bright star in blob
MB_BAIL =                 1024 / Maskbit: bailed-out processing
MB_MED  =                 2048 / Maskbit: medium-bright star in blob
MB_GAL  =                 4096 / Maskbit: LSLGA large galaxy
MB_CLUST=                 8192 / Maskbit: Cluster
MB_SAT_G=                    4 / Maskbit: saturated (& nearby), g band
MB_SAT_R=                    8 / Maskbit: saturated (& nearby), r band
MB_SAT_Z=                   16 / Maskbit: saturated (& nearby), z band
MB_ALL_G=                   32 / Maskbit: ALLMASK band g
MB_ALL_R=                   64 / Maskbit: ALLMASK band r
MB_ALL_Z= …
```
=> Changes to bitmasks and headers

py/legacypipe/runbrick.py
Evaluate positions of Gaia stars at each image epoch and avoid detecting new stars there.
=> Suppress additional source detections along moving Gaia star tracks

py/legacypipe/detection.py, py/legacypipe/farm.py, py/legacypipe/oneblob.py, py/legacypipe/reference.py, py/legacypipe/runbrick.py
- expand search radius for SGA galaxies to twice their ellipse radii
- find these "frozen galaxies" and add special handling for them:
- remove them from the blob-to-sources mapping, unless they're actually in bounds of the brick
- in oneblob, subtract them from the tims before we start anything else
- when rendering model images: render these frozen galaxies; mask them to all the blobs that their maskbits map would touch (with twice the radius) for the blobmodel images; remove them from the other sources to be fit (for the case where the galaxy is actually inside the brick)
=> Extend frozen SGA galaxy profiles outside their blob & brick

py/legacyzpts/legacy_zeropoints.py
This hopes to fix the bug @djschlegel reported in [decam-chatter 13012]
where
mosaic/CP/V4.3/CP20151213/k4m_151214_064908_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20160219/k4m_160220_094004_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20170206/k4m_170207_070400_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20170831/k4m_170901_121112_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20171101/k4m_171102_125607_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20170804/k4m_170805_115147_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20170808/k4m_170809_102618_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20170909/k4m_170910_121742_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20180102/k4m_180103_083355_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20170310/k4m_170311_061642_ooi_zd_ls9.fits.fz
mosaic/CP/V4.3/CP20170505/k4m_170506_040128_ooi_zd_ls9.fits.fz
produce NaN zero points. …
=> Remove NaN dmags from zpt calculation earlier.

py/legacypipe/fit_on_coadds.py, py/legacypipe/runbrick.py
Adds a new keyword, `--ubercal-sky` which is only used with `--fit-on-coadds` and `--no-subsky`. For use with, e.g., M33.
=> [WIP] restore ubercal sky-subtraction option in fit_on_coadds

py/legacypipe/image.py, py/legacyzpts/legacy_zeropoints.py
Previously, we used to write out the table that will become the survey-ccds file, and then annotate it to make the annotated-ccds table.  Later, we dropped that and just write the annotated one, then cut it down to the survey-ccds file.  But the code internally still wrote out the initial file, then re-read it and annotated it before writing out the annotated file.  Drop that.
=> drop surveyfn and intermediate un-annotated CCDs table altogether

bin/generate-sweep-files.py
This PR adds the `FITBITS` column to the sweeps. It's a rather unassuming PR, but I at least checked that the branch runs to completion to create the sweeps files (with `FITBITS`) from the dr9k tractor catalogs.
=> add the FITBITS column to the sweeps files

py/legacyzpts/data/mosaic-bad_expid.txt
Adding a few exposures with an artifact from a nearby bright star to the bad_expid list.  The hope is that adding these will let the outlier rejection trigger on this feature.  Documented in
[decam-chatter 13589] Bright star reflection from red star in mosaic
https://desi.lbl.gov/mailman/private/decam-chatter/2020-August/013588.html
=> Add CCD4 on few exposures on one pointing near a bright star to bad_expid to allow outlier masking.  

py/legacypipe/oneblob.py, py/legacypipe/reference.py, py/legacypipe/runbrick.py
saturated and SGA-preburn sources have poor initial flux estimates.
mark them with a "need_initial_flux" attribute.
fit just the fluxes of those sources at the beginning.
(and drop initial fitting of all fluxes for small blobs)
=> mark sources that need initial flux estimates

bin/dr9-sweeps-and-external.sh, bin/generate-sweep-files.py, bin/match-external-catalog.py, py/legacypipe/internal/io.py
This PR should address #648 and #649. It adds:
- Units to sweeps and external-match files.
- A git-hash with the version of the code used by `generate-sweep-files.py` or `match-external-catalog.py`.
- A dr9 version of the slurm scrips used to generate sweeps files and match to external catalogs.
* Rather than updating the existing slurm scrips, I added a new script `dr9-sweeps-and-external.sh`. The old scripts had fallen behind the north/south split and use of docker containers.
=> Update production script and add units to sweeps/external-match files

bin/match-external-catalog.py
@rongpu noticed that our files of LS sources matched to external spectroscopy miss any duplicates in the external catalogs. This PR modifies `bin/match-external-catalog.py` to include all of the duplicates in the matching process.
=> Include duplicates when constructing the external-match catalogs

bin/dr9-sweeps-and-external.sh, bin/generate-sweep-files.py
This PR splits the sweeps into 3 separate sets of files:
1. The original sweeps.
2. All of the columns that correspond to light curves.
3. The remaining columns that aren't in (1.) or (2.) but are in the Tractor files.
The data model looks like, for example:
```
1. north/sweep/X.X/sweep-330p030-340p035.fits
2. north/sweep/X.X-lightcurves/sweep-330p030-340p035-lc.fits
3. north/sweep/X.X-extra/sweep-330p030-340p035-ex.fits
```
where the intention would be for `X.X` to be changed to the appropriate data release (`9.1`, etc.).
=> Split sweeps into three sets of files

bin/dr9-sweeps-and-external.sh
This PR just fixes a typo where I used the string "dr16q" instead of "dr16Q" when naming the "external superset" file. 
This is likely to be uncontroversial, so I'll merge it later today.
=> External superset file should be named dr16Q not dr16q

py/legacypipe/coadds.py, py/legacypipe/fit_on_coadds.py, py/legacypipe/runbrick.py
For low surface-brightness work, where the default spline sky-subtraction can be problematic, allow the `--subsky_radii` optional input to be a vector of annuli.  Only used with `--fit-on-coadds`, `--no-subsky` and `--ubercal-sky`.
Also optionally write out additional header cards by passing a dictionary (`coadd_headers`) with a key / header card and value, comment tuple.
Not quite ready to merge. Need to clean up the documentation a bit.
=> generalize annular sky-subtraction options

py/legacypipe/runbrick.py
perform fiberflux aperture photometry at the source's position in the synthetic image (not fit brick pixel position)
=> Fix fiberflux error for moving (Gaia) point sources.

py/legacypipe/deep-preprocess.py, py/legacypipe/depthcut.py, py/legacypipe/forced_photom.py, py/legacypipe/halos.py, py/legacypipe/outliers.py, py/legacypipe/runbrick.py
In bricks with many exposures, run preprocessing on individual CCDs at a time, avoiding huge memory use.  This produces:
- image coadds & invvars
- detection maps
- outliers masks
The outlier masks are somewhat different than the main pipeline.  The images and invvars are very similar.
=> Deep preprocessing

py/legacypipe/galex.py, py/legacypipe/runbrick.py
Simple PR. Adds the option of not using the Ceres solver when performing GALEX forced photometry.
=> add --no-galex-ceres option
